language: php

php:
  - 7.2

before_script:
  - cp .env.example .env
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan migrate

script:
  - vendor/bin/phpunit

before_install:
  - mysql -e 'create database irabu;'

services:
  - mysql
  
cache:
  - directories:
      - vendor
      - node_modules